---

- name: "Fail if there are too many backlog commands"
  fail:
    msg: "Too many backlog commands ({{ tasmota_backlog_commands | length }}), cannot be more than 30."
  when: "tasmota_backlog_commands | length > 30"

- name: "Configure tasmota"
  tasmota:
    command: "{{ item.command }}"
    value: "{{ item.value }}"
  no_log: "{{ item.no_log | default(omit) }}"
  with_items: "{{ tasmota_commands }}"

- name: Test
  debug:
    msg: "{% for item in tasmota_backlog_commands %}{{ item.command }} {{ item.value }};{% endfor %}"

# Have to do it this way, if one Backlog ist called while another one is running, the first one gets cancelled
- name: "Run important commands as bulk via backlog"
  tasmota:
    command: "Backlog"
    value: "{% for item in tasmota_backlog_commands %}{{ item.command }} {{ item.value }};{% endfor %}"
  no_log: false
